### ISSUE TITLE
chi in qaa_cdom

### ISSUE THREAD

**Issue by khondula** [CMLandOcean/bio_optics#10]
https://github.com/CMLandOcean/bio_optics/blob/9321d04883bec2b8b7ce0c61ef16822c85d71787/bio_optics/models/qaa.py#L158

in the QAA CDOM model equation 10 in the paper it looks like its R_rs values, but on line in the package its r_rs

**Comment by mkoenig3** [comment]
Thanks! :) ... this is resolved now.
